### ISSUE TITLE
MediaWiki key wgDBprefix does not exist

### ISSUE THREAD

**Issue by YSmetana** [tetsuo13/MediaWiki-to-DokuWiki-Importer#25]
Hi! I am getting the following error:

    root@vm103:/var/www/dokuwiki/src/MediaWiki2DokuWiki# php index.php 
    MediaWiki key wgDBprefix does not exist

My **LocalSettings.php**:

    # MySQL specific settings
    $wgDBprefix         = "";

**Comment by valx76** [comment]
Hi, the problem is still here..

As the script does not accept empty wgDBprefix, you can replace `$mediaWikiSettings->getSetting('wgDBprefix')` with `''` at the **Environment.php** file.

That worked !

**Comment by tetsuo13** [comment]
So the bug that remains here is that `$wgDBprefix` may not exist at all which would be the same thing as if it were `$wgDBprefix = ''`
