### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by AlasdairKing** [tetsuo13/MediaWiki-to-DokuWiki-Importer#30]
MySQL, PHP 5.4.11.

I'm pretty sure I've set mediawiki_localsettings_file and dokuwiki_dir correctly by virtue of shoving in a couple of echo PHP statements. 

MediaWiki still works. DokuWiki works. 

What next?

**Comment by samwilson** [comment]
Did anyone ever figure this problem out? I'm getting the same issue.

**Comment by AlasdairKing** [comment]
I didn't. Stayed with MediaWiki and upgraded the server...

**Comment by tetsuo13** [comment]
I think the issue may not be related to paths for files but rather caused by the SQL connection. Maybe unix sockets are being used? If the database server is on the same machine, try "127.0.0.1" instead of "localhost" for the DB settings?

**Comment by samwilson** [comment]
hm... yes, it's certainly coming from mysql, but not the host... i'll keep digging... :) Thanks

**Comment by AlasdairKing** [comment]
Closed since I'm not using this project.
