### ISSUE TITLE
"PHP Fatal error:  Cannot redeclare ..."

### ISSUE THREAD

**Issue by Goldenmenu** [tetsuo13/MediaWiki-to-DokuWiki-Importer#36]
Hi,
I tried to run the script to convert my Mediawiki to Dokuwiki. Both directory are stored on the same physical server (Synology).
src directory is on the web folder. 
I wrote the absolute path of both Mediawiki and Dokuwiki. Each time I launch the script (SSH) it returns the following error  
`Fatal error: Cannot redeclare hsc() (previously declared in /volume1/web/dokuwiki/inc/common.php:30) in /volume1/web/dokuwiki/inc/common.php on line 32`

I have not seen anyone else having this issue with this script. So I guess I missed an important step but I cannot find where. 
Here's some informations about the installation
PHP 5.6
Mediawiki 1.26.2
Dokuwiki 2016-06-26a "Elenor of Tsort"
Server DSM 6.0.2
Maria DB 5.5

Thanks a lot

**Comment by tetsuo13** [comment]
I think this may have been introduced by #33 which loads `common.php` but I can't be sure. DokuWiki has quite a few include files which load further include files and somewhere in there this file was loaded twice.

I've addressed this by ensuring each include file is loaded only once. Please try again using master.

**Comment by Goldenmenu** [comment]
Thank you for your quick reply. 
I still have error with this new version : 
`PHP Fatal error:  Call to undefined function token_get_all() in /volume1/web/MW2DW_2/src/MediaWiki2DokuWiki/MediaWiki/Settings.php on line 163`

**Comment by tetsuo13** [comment]
Strange. [`token_get_all()`](https://php.net/token_get_all) is a PHP function. Can you paste the output of `php -v`?

**Comment by Goldenmenu** [comment]
Thanks to [this post ](https://forum.synology.com/enu/viewtopic.php?t=115878)I found out Synology servers have several php command line : 
"php" wich is an old version without tokenizer built-in
"php56" with tokenizer
I tried MW2DW converter with this one and it seems to work. 
By the way, the result of `php -v`
```
PHP 5.6.11 (cli) (built: Aug 17 2016 05:52:14) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```
and `php56 -v`
```
PHP 5.6.21 (cli) (built: May 13 2016 19:44:10) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
Thank you for your replies.

**Comment by tetsuo13** [comment]
That's interesting. I suppose that the default PHP binary available was compiled without tokenizer support. The [installation page](https://secure.php.net/manual/en/tokenizer.installation.php) notes the flags for it. I was originally thinking that perhaps the version of PHP you had was too old but turns out its a compilation flag issue. `php -i | grep -i token` shouldn't find anything while using `php56` should.
