### ISSUE TITLE
Could not fetch MediaWiki: Unknown column 'r.rev_text_id' in 'on clause'

### ISSUE THREAD

**Issue by bcnx** [tetsuo13/MediaWiki-to-DokuWiki-Importer#40]
Hi,

I get this error when using MediaWiki 1.35. I suspect this version is too recent for this import tool, but I cannot downgrade. 
Can this error be fixed?

Cheers,

BC

**Comment by tetsuo13** [comment]
The last version of MediaWiki tested was 1.17.1. It's likely something's changed in how the text on pages are stored internally since then.

**Comment by bcnx** [comment]
Right, I suppose that is to be expected when development has ceased. For posterity: I was able to get things working with yamdwe. 

Cheers,

BC

**Comment by tetsuo13** [comment]
Thanks for the mention of the yamdwe project. I've added a link to it in the README for others to utilize as an alternative to this project.
